/*
 *          ::::::::  :::       :::     :::     :::::::::  :::::::::   ::::::::
 *         :+:    :+: :+:       :+:   :+: :+:   :+:    :+: :+:    :+: :+:    :+:
 *         +:+    +:+ +:+       +:+  +:+   +:+  +:+    +:+ +:+    +:+ +:+    +:+
 *         +#+    +:+ +#+  +:+  +#+ +#++:++#++: +#+    +:+ +#++:++#:  +#+    +:+
 *         +#+  # +#+ +#+ +#+#+ +#+ +#+     +#+ +#+    +#+ +#+    +#+ +#+    +#+
 *         #+#   +#+   #+#+# #+#+#  #+#     #+# #+#    #+# #+#    #+# #+#    #+#
 *          ###### ###  ###   ###   ###     ### #########  ###    ###  ########
 *
 *        Q W A D R O   V I D E O   G R A P H I C S   I N F R A S T R U C T U R E
 *
 *                                   Public Test Build
 *                               (c) 2017 SIGMA FEDERATION
 *                             <https://sigmaco.org/qwadro/>
 */

  //////////////////////////////////////////////////////////////////////////////
 // QWADRO FORMATTED VIDEO MEMORY BUFFER                                     //
//////////////////////////////////////////////////////////////////////////////

// This code is part of SIGMA GL/2 <https://sigmaco.org/gl>

/*
    A list of function declarations related to raster operations in a graphics or rendering API, 
    related to the management and manipulation of raster data (such as textures or images) in a drawing system.

    These functions are used to interact with raster data in a graphics system, likely within a GPU or rendering context. 
    They include operations for testing usage and flags, querying properties, manipulating textures (or images), 
    and transferring data between the system and the GPU or storage.
*/

#ifndef AVX_RASTER_H
#define AVX_RASTER_H

#include "qwadro/inc/draw/io/avxFormat.h"
#include "qwadro/inc/io/afxUri.h"
#include "qwadro/inc/draw/op/avxSampler.h"
#include "qwadro/inc/math/afxWhd.h"
#include "qwadro/inc/draw/op/avxTransference.h"
#include "qwadro/inc/draw/math/avxViewport.h"
 
#define AVX_RASTER_ALIGNMENT (256)

typedef enum avxRasterUsage
{
    avxRasterUsage_SRC      = AFX_BITMASK(0), // The texture can be used as the source of a copy operation.
    avxRasterUsage_DST      = AFX_BITMASK(1), // The texture can be used as the destination of a copy or write operation.
    avxRasterUsage_TRANSFER = (avxRasterUsage_SRC | avxRasterUsage_DST),
    avxRasterUsage_RESAMPLE = AFX_BITMASK(2), // The texture can be bound for use as a sampled texture in a shader.
    avxRasterUsage_STORAGE  = AFX_BITMASK(3), // The texture can be bound for use as a storage texture in a shader.
    avxRasterUsage_DRAW     = AFX_BITMASK(4), // The texture can be used as a color or depth/stencil attachment in a draw scope.
    avxRasterUsage_VIDEO    = (avxRasterUsage_RESAMPLE | avxRasterUsage_DRAW),

    avxRasterUsage_ALL      = avxRasterUsage_TRANSFER | avxRasterUsage_RESAMPLE | avxRasterUsage_STORAGE | avxRasterUsage_DRAW,
} avxRasterUsage;

typedef enum avxRasterFlag
{
    avxRasterFlag_LAYERED   = AFX_BITMASK(0), // has more than 1 layer/slice (or a set of them, in case of cubemap).
    avxRasterFlag_MIPMAP    = AFX_BITMASK(1), // has more than 1 LOD, which are subsamples from base image; (aka mipmaps).
    avxRasterFlag_UPSAMPLED = AFX_BITMASK(2), // has more than 1 LOD, which are supersamples from base image; (aka multisample).
    avxRasterFlag_CUBEMAP   = AFX_BITMASK(3), // is one or more maps of a cubemapping texture.
    
    // autogenerated by acquisition if omitted.
    avxRasterFlag_1D        = AFX_BITMASK(4), // expands only into its width as a linear buffer.
    avxRasterFlag_2D        = AFX_BITMASK(5), // a common rectangular image.
    avxRasterFlag_3D        = AFX_BITMASK(6), // depth is not layer but volumetric extent.

#if !0
    avxRasterFlag_ROW_MAJOR = AFX_BITMASK(9), // specifies linear tiling (texels are laid out in memory in row-major order, possibly with some padding on each row).
    //avxRasterFlag_OPTIMAL = AFX_BITMASK(10), // specifies optimal tiling (texels are laid out in an implementation-dependent arrangement, for more efficient memory access).    
#endif
} avxRasterFlags;

AFX_DEFINE_STRUCT(avxRasterLayout)
/// Information about the layout of the raster subresource.
{
    afxSize         offset; // the byte offset from the start of the raster or the plane where the raster subresource begins.
    afxUnit         size; // the size in bytes of the raster subresource. siz includes any extra memory that is required based on rowStride.
    afxUnit         rowStride; // the number of bytes between each row of texels in an raster.
    afxUnit         imgStride; //  the number of bytes between each layer or (3D) slice of an raster.
};

AFX_DEFINE_STRUCT(avxRasterInfo)
{
    avxFormat       fmt;
    afxUnit         lodCnt; // mipmaps or supersamples, depending on flags. Default is mipmap.
    avxRange        extent;
    avxRasterUsage  usage;
    avxRasterFlags  flags;

    afxMask         exuMask;
    
    // subresourcing
    avxRaster       base;
    afxUnit         baseLod;
    afxUnit         baseLayer;
    avxSwizzling    swizzle;

    void*           udd;
    afxString       tag;
};

// LOD is mip level or sample level, depending on raster

/*
    The AvxTestRasterUsage() function tests the usage flags of a raster and 
    returns whether the raster is used in specific ways defined by the mask.
*/

AVX avxRasterUsage  AvxTestRasterUsage
(
    avxRaster ras, 
    avxRasterUsage mask
);

/*
    The AvxTestRasterFlags() function tests specific flags (probably for state or attributes) of the raster and 
    returns whether those flags are set.
*/

AVX avxRasterFlags  AvxTestRasterFlags
(
    avxRaster ras, 
    avxRasterFlags mask
);

/*
    The AvxDescribeRaster() function provides detailed information about the raster, 
    storing the result in the provided avxRasterInfo structure.
*/

AVX void AvxDescribeRaster
(
    avxRaster ras, 
    avxRasterInfo* desc
);

/*
    The AvxGetRasterFormat() function returns the format of the raster (e.g., pixel format, bit depth).
*/

AVX avxFormat AvxGetRasterFormat
(
    avxRaster ras
);

/*
    The AvxDescribeRasterFormat() function describes the raster's format capabilites in a given bridge.
*/

AVX avxFormat AvxDescribeRasterFormat
(
    avxRaster ras, 
    afxMask exuMask, 
    avxFormatDescription* pfd
);

/*
    The AvxGetRasterExtent() function retrieves the extent (size or dimensions) of a raster at a particular 
    level of detail (LOD), specified by lodIdx.
*/

AVX avxRange AvxGetRasterExtent
(
    avxRaster ras, 
    afxUnit lodIdx
);

/*
    The AvxGetRasterSwizzling() function gets the color swizzling for a given sub-index of a raster (typically for GPU color format mapping).
*/

AVX void AvxGetRasterSwizzling
(
    avxRaster ras, 
    avxSwizzling* csw
);

/*
    The AvxQueryRasterLayout() function queries the layout of a raster at a given LOD and layer index, potentially for more detailed memory access patterns.
*/

AVX afxBool AvxQueryRasterLayout
(
    avxRaster ras, 
    afxUnit lodIdx, 
    afxUnit layerIdx, 
    avxRasterLayout* layout
);

////////////////////////////////////////////////////////////////////////////////

/*
    The AvxAcquireRasters() function acquires multiple rasters (textures or images) for use in a drawing system, based on the provided avxRasterInfo.
*/

AVX afxError AvxAcquireRasters
(
    afxDrawSystem dsys, 
    afxUnit cnt, 
    avxRasterInfo const info[], 
    avxRaster rasters[]
);

#endif//AVX_RASTER_H
